server:
  port: 80
  address: 127.0.0.1
jasypt:
  encryptor:
    password: 123123


spring:
  datasource:
    url: jdbc:mysql://127.0.0.1/weibo
    username: root
    password:
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
  thymeleaf:
   cache: false
   prefix: classpath:/view/
   suffix: .html
   encoding: UTF-8
   content-type: text/html
   mode: HTML5